//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHoaDonNhap
    {
        public string MaHDN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
    
        public virtual tChiTietHDN tChiTietHDN { get; set; }
        public virtual tNhaCungCap tNhaCungCap { get; set; }
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
