//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietHoaDon
    {
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public Nullable<double> GiaTienSP { get; set; }
    
        public virtual tHoaDonBan tHoaDonBan { get; set; }
        public virtual tSanPham tSanPham { get; set; }
    }
}
