//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongLuong
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<int> TongCaLam { get; set; }
        public Nullable<decimal> TongLuong1 { get; set; }
    
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
