//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSanPham()
        {
            this.tChiTietHDN = new HashSet<tChiTietHDN>();
            this.tChiTietHoaDon = new HashSet<tChiTietHoaDon>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public string loaiSP { get; set; }
        public string Anh { get; set; }
        public string MaLoai { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual tAnh tAnh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHDN> tChiTietHDN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHoaDon> tChiTietHoaDon { get; set; }
        public virtual tLoaiSP tLoaiSP { get; set; }
    }
}
