//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTkNhanVien
    {
        public int maTK { get; set; }
        public string MaNV { get; set; }
        public string tenTK { get; set; }
        public string matKhau { get; set; }
    
        public virtual tNhanVien tNhanVien { get; set; }
    }
}
